apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    role: exporter
    release: prometheus
  name: elasticsearch-exporter
  namespace: elasticsearch
spec:
  jobLabel: elasticsearch
  podMetricsEndpoints:
  - interval: 30s
    port: scrape
    path: /metrics
  selector:
    matchLabels:
      role: exporter