kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-pv-claim-replicated
spec:
  storageClassName: fast-replicated
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench-replicated
spec:
  template:
    spec:
      containers:
      - name: fio-test
        image: <repo>/dbench:1.0.0
        imagePullPolicy: Always
        env:
          - name: FIO_MOUNTPOINT
            value: /data
          # - name: FIO_QUICK
          #   value: "yes"
          - name: FIO_SIZE
            value: 10G
          - name: RUN_TIME
            value: 900s
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: fio-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: fio-pv
        persistentVolumeClaim:
          claimName: fio-pv-claim-replicated
  backoffLimit: 4
