apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    etcd_cluster: storageos-etcd
  name: etcd-storageos
  namespace: etcd
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
    etcd_cluster: storageos-etcd
  type: ClusterIP