{
 "title": "Kubernetes Kafka",
 "description": "Global Kafka dashboard running on Kubernetes",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value, namespace)"
   },
   {
    "name": "broker",
    "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "zookeeper",
    "query": "label_values(cp_zookeeper_tick{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", pod=~\"my-kafka-[0-9]\"}) / 3"
    }
   ]
  },
  {
   "title": "Number of brokers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_brokers{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Active controller status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "In-sync replicas shrinks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrshrinkspersec_count{namespace=\"$namespace\", pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Partition count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{namespace=\"$namespace\", pod=\"$broker\"}"
    }
   ]
  },
  {
   "title": "Broker status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\", pod=\"$broker\"}"
    }
   ]
  },
  {
   "title": "Unclean leader election",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec_count{namespace=\"$namespace\", pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\"} == 1"
    }
   ]
  },
  {
   "title": "In-sync replicas expands",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrexpandspersec_count{namespace=\"$namespace\", pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Offline partitions count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{namespace=\"$namespace\", pod=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Bytes rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_count{namespace=\"$namespace\", pod=~\"$broker\"} / kafka_server_brokertopicmetrics_total_bytesoutpersec_count{namespace=\"$namespace\", pod=~\"$broker\"}",
     "legendFormat": "Broker {{ pod }}"
    }
   ]
  },
  {
   "title": "Messages IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{namespace=\"$namespace\", pod=~\"$broker\"}",
     "legendFormat": "{{ pod }} {{ value }}"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{namespace=\"$namespace\", pod=~\"$broker\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{namespace=\"$namespace\", pod=~\"$broker\"}[5m])",
     "legendFormat": "Broker {{ pod }}"
    }
   ]
  },
  {
   "title": "In-sync replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- kafka_server_replicamanager_total_isrshrinkspersec_count{namespace=\"$namespace\", pod=~\"$broker\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{namespace=\"$namespace\", pod=~\"$broker\", area=\"heap\"}",
       "legendFormat": "used {{ pod }}"
      },
      {
       "expr": "jvm_memory_bytes_max{namespace=\"$namespace\", pod=~\"$broker\", area=\"heap\"}",
       "legendFormat": "max {{ pod }}"
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_systemcpuload{namespace=\"$namespace\", pod=~\"$broker\"} * 100",
       "legendFormat": "system {{ pod }}"
      },
      {
       "expr": "java_lang_operatingsystem_processcpuload{namespace=\"$namespace\", pod=~\"$broker\"} * 100",
       "legendFormat": "process {{ pod }}"
      }
     ]
    },
    {
     "title": "Garbage collection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "s", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", pod=~\"$broker\"}[5m])) without(gc)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "System load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_systemloadaverage{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "System load average"
      },
      {
       "expr": "java_lang_operatingsystem_availableprocessors{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Available Processors"
      }
     ]
    },
    {
     "title": "Open file descriptor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_openfiledescriptorcount{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "System memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "java_lang_operatingsystem_totalphysicalmemorysize{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Total memory {{ pod }}"
      },
      {
       "expr": "java_lang_operatingsystem_freephysicalmemorysize{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Free memory {{ pod }}"
      },
      {
       "expr": "java_lang_operatingsystem_totalswapspacesize{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Total SWAP  {{ pod }}"
      },
      {
       "expr": "java_lang_operatingsystem_freeswapspacesize{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Free SWAP  {{ pod }}"
      },
      {
       "expr": "java_lang_operatingsystem_committedvirtualmemorysize{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Committed virtual memory {{ pod }}"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Loaded {{ pod }}"
      },
      {
       "expr": "jvm_classes_loaded_total{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Total loaded {{ pod }}"
      },
      {
       "expr": "jvm_classes_loaded_total{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Unloaded {{ pod }}"
      },
      {
       "expr": "delta(jvm_classes_loaded{namespace=\"$namespace\", pod=~\"$broker\"}[5m])",
       "legendFormat": "Delta {{ pod }}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Current {{ pod }}"
      },
      {
       "expr": "jvm_threads_daemon{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Daemon {{ pod }}"
      },
      {
       "expr": "jvm_threads_deadlocked{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Deadlock {{ pod }}"
      },
      {
       "expr": "jvm_threads_peak{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Peak {{ pod }}"
      },
      {
       "expr": "jvm_threads_started_total{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "Started total {{ pod }}"
      }
     ]
    },
    {
     "title": "Total memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 36 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(java_lang_operatingsystem_totalphysicalmemorysize{namespace=\"$namespace\", pod=~\"$broker\"})"
      }
     ]
    },
    {
     "title": "Total CPUs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(java_lang_operatingsystem_availableprocessors{namespace=\"$namespace\", pod=~\"$broker\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", pod=~\"$broker\", request=\"Produce, version=6\"}",
       "legendFormat": "{{ pod }} produce"
      },
      {
       "expr": "kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", pod=~\"$broker\", request=\"FetchConsumer, version=8\"}",
       "legendFormat": "{{ pod }} fetch consumer"
      },
      {
       "expr": "kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", pod=~\"$broker\", request=\"FetchFollower, version=8\"}",
       "legendFormat": "{{ pod }} fetch follower"
      }
     ]
    },
    {
     "title": "Purgatory delayed fetch operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_fetch_value{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Log size by broker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_log_log_size{namespace=\"$namespace\"}) by(pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "All number of requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", pod=~\"$broker\"}) by (request)",
       "legendFormat": "{{ request }}"
      }
     ]
    },
    {
     "title": "Idle network processors",
     "type": "graph",
     "description": "The average fraction of time the network processors are idle",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_network_processor_idlepercent_value{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "{{ pod }} network processor {{ network_processor }}"
      }
     ]
    },
    {
     "title": "Idle request handler threads",
     "type": "graph",
     "description": "The average fraction of time the request handler threads are idle",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{namespace=\"$namespace\", pod=~\"$broker\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Quorum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_quorumsize{namespace=\"$namespace\"}) / 3"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cp_zookeeper_ticktime{namespace=\"$namespace\", membertype=\"Leader\"}"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_outstandingrequests{namespace=\"$namespace\", pod=~\"$zookeeper\"})"
    }
   ]
  },
  {
   "title": "ZNodes count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cp_zookeeper_inmemorydatatree_nodecount{namespace=\"$namespace\", membertype=\"Leader\"}"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cp_zookeeper_inmemorydatatree_watchcount{namespace=\"$namespace\", pod=~\"$zookeeper\"})"
    }
   ]
  },
  {
   "title": "Requests latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "cp_zookeeper_avgrequestlatency{namespace=\"$namespace\", pod=~\"$zookeeper\"}",
     "legendFormat": "Average {{ pod }}"
    },
    {
     "expr": "cp_zookeeper_maxrequestlatency{namespace=\"$namespace\", pod=~\"$zookeeper\"}",
     "legendFormat": "Max {{ pod }}"
    },
    {
     "expr": "cp_zookeeper_minrequestlatency{namespace=\"$namespace\", pod=~\"$zookeeper\"}",
     "legendFormat": "Min {{ pod }}"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_zookeeper_outstandingrequests{namespace=\"$namespace\", pod=~\"$zookeeper\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_zookeeper_packetsreceived{namespace=\"$namespace\", pod=~\"$zookeeper\"}",
     "legendFormat": "Received {{ pod }}"
    },
    {
     "expr": "cp_zookeeper_packetssent{namespace=\"$namespace\", pod=~\"$zookeeper\"}",
     "legendFormat": "Sent {{ pod }}"
    }
   ]
  }
 ]
}